### ISSUE TITLE
When will the CODE get released ?

### ISSUE THREAD

**Issue by Changee-git** [imguangyu/FedPerfix#1]
hello, devs or researchers, I am intrigued about your work. It's awesome and promising. I scheduled to reproduce the code mentioned in your paper. Thus, I'd love to request for the time you nice guys release the code.

**Comment by imguangyu** [comment]
Thank you for your interest! We are still working on cleaning the code prior to release. Our current estimate is to have it ready before the end of November.

**Comment by Tinghao-Chen** [comment]
Your work inspired me, I’m looking forward to read the code.

**Comment by imguangyu** [comment]
We are in the final stage of releasing the code to improve the readability and consistency. We will try our best to release it this weekend. Thanks for your patience!

**Comment by imguangyu** [comment]
We've released a version with the introductions to reproduce our main results. Please let us know if there is any question. Thanks for your interest in our work!
